In [21]:
#import library
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [24]:
dataset = pd.read_csv('Dataset.csv')
x = dataset.iloc[:, :-1].values
y = dataset.iloc[:, -1].values

In [25]:
print(x)

[[' Banjarnegara ' 1023.0 nan]
 [' Banyumas' 1335.0 1970000.0]
 [' Batang' 788.0 2129117.0]
 [' Batang' 1804.0 1894000.0]
 [' Banyumas' 1008.0 2000000.0]
 [' Banjarnegara' 1902.0 1866722.0]
 [' Banyumas' 2124.0 2228904.0]
 [' Batang' nan 2511526.0]
 [' Banjarnegara' 2013.0 1890000.0]]


In [26]:
print(y)

['Yes' 'Yes' 'No' 'Yes' 'No' 'Yes' 'No' 'No' 'Yes']


In [27]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan, strategy='mean')
imputer.fit(x[:, 1:3])
x[:, 1:3] = imputer.transform(x[:, 1:3])

In [28]:
print(x)

[[' Banjarnegara ' 1023.0 2061283.625]
 [' Banyumas' 1335.0 1970000.0]
 [' Batang' 788.0 2129117.0]
 [' Batang' 1804.0 1894000.0]
 [' Banyumas' 1008.0 2000000.0]
 [' Banjarnegara' 1902.0 1866722.0]
 [' Banyumas' 2124.0 2228904.0]
 [' Batang' 1499.625 2511526.0]
 [' Banjarnegara' 2013.0 1890000.0]]


In [29]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder',OneHotEncoder(), [0])], remainder='passthrough')
x = np.array(ct.fit_transform(x))

In [30]:
print(x)

[[0.0 1.0 0.0 0.0 1023.0 2061283.625]
 [0.0 0.0 1.0 0.0 1335.0 1970000.0]
 [0.0 0.0 0.0 1.0 788.0 2129117.0]
 [0.0 0.0 0.0 1.0 1804.0 1894000.0]
 [0.0 0.0 1.0 0.0 1008.0 2000000.0]
 [1.0 0.0 0.0 0.0 1902.0 1866722.0]
 [0.0 0.0 1.0 0.0 2124.0 2228904.0]
 [0.0 0.0 0.0 1.0 1499.625 2511526.0]
 [1.0 0.0 0.0 0.0 2013.0 1890000.0]]


In [31]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y)

In [32]:
print(y)

[1 1 0 1 0 1 0 0 1]


In [33]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state = 1)

In [34]:
print(x_train)

[[0.0 0.0 1.0 0.0 2124.0 2228904.0]
 [0.0 0.0 0.0 1.0 1499.625 2511526.0]
 [0.0 0.0 1.0 0.0 1335.0 1970000.0]
 [0.0 1.0 0.0 0.0 1023.0 2061283.625]
 [0.0 0.0 1.0 0.0 1008.0 2000000.0]
 [0.0 0.0 0.0 1.0 1804.0 1894000.0]
 [1.0 0.0 0.0 0.0 1902.0 1866722.0]]


In [35]:
print(x_test)

[[1.0 0.0 0.0 0.0 2013.0 1890000.0]
 [0.0 0.0 0.0 1.0 788.0 2129117.0]]


In [36]:
print(y_train)

[0 0 1 1 0 1 1]


In [37]:
print(y_test)

[1 0]


In [38]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
x_train[:, 3:] = sc.fit_transform(x_train[:, 3:])
x_test[:, 3:] = sc.transform(x_test[:, 3:])

In [39]:
print(x_train)

[[0.0 0.0 1.0 -0.6324555320336758 1.4804194075482409 0.7295780057884463]
 [0.0 0.0 0.0 1.5811388300841895 -0.07034198688910748 2.0786516133684563]
 [0.0 0.0 1.0 -0.6324555320336758 -0.47922141761463055
  -0.5062796178109017]
 [0.0 1.0 0.0 -0.6324555320336758 -1.254136420720861 -0.07054450415474328]
 [0.0 0.0 1.0 -0.6324555320336758 -1.2913919497163528 -0.3630770071599251]
 [0.0 0.0 0.0 1.5811388300841895 0.685634788977748 -0.8690595647933756]
 [1.0 0.0 0.0 -0.6324555320336758 0.9290375784149614 -0.9992689252379536]]


In [40]:
print(x_test)

[[1.0 0.0 0.0 -0.6324555320336758 1.2047284929816011 -0.8881532462135059]
 [0.0 0.0 0.0 1.5811388300841895 -1.8378063749835667 0.25325270882081297]]
